---
- name: Install Arch Linux packages
  hosts: localhost
  become: true
  gather_facts: false

  collections:
    - community.general

  vars:
    # Core system packages
    system_packages:
      - networkmanager
      - sudo
      - base-devel
      - which
      - nvim
      - less
      - man
      - tree
      - tmux
      - git
      - pacman-contrib
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack
      - pavucontrol
      - wireplumber
      - rtkit
      - reflector
      - rsync
      - openssh
      - unzip
      - ripgrep
      - btop
      - dysk
      - fzf
      - atuin
      - yazi
      - ark
      - dolphin
      - shellcheck
      - cmake
      - solaar
      - stow
      - starship
      - playerctl
      - zoxide
      - bluez
      - bluez-utils
      - blueman
      - ghostty

    custom_become_user: "vijay"

  tasks:
    - name: Update package database
      community.general.pacman:
        update_cache: yes
      register: pacman_update

    - name: Install system packages
      community.general.pacman:
        name: "{{ system_packages }}"
        state: present
        update_cache: no

    - name: Remove existing yay build directory if present
      ansible.builtin.file:
        path: /tmp/yay
        state: absent

    - name: Create yay build directory with user ownership
      ansible.builtin.file:
        path: /tmp/yay
        state: directory
        owner: "{{ custom_become_user }}"
        group: "{{ custom_become_user }}"
        mode: "0755"
    
    - name: Clone yay AUR repository
      ansible.builtin.git:
        repo: "https://aur.archlinux.org/yay.git"
        dest: /tmp/yay
        clone: yes
        update: no
        depth: 0
      become: true
      become_user: "{{ custom_become_user }}"


    - name: Build and install yay from AUR
      ansible.builtin.command:
        cmd: makepkg -si --noconfirm -- -buildvcs=false
        chdir: /tmp/yay
      become: true
      become_user: "{{ custom_become_user }}"
      args:
        creates: /usr/bin/yay

    - name: Clean up yay build directory
      ansible.builtin.file:
        path: /tmp/yay
        state: absent
