---
- name: Install Hyprland packages
  hosts: localhost
  become: true
  gather_facts: false

  vars:
    # Hyprland packages
    hyprland_packages:
      - nvidia
      - nvidia-utils
      - nvidia-settings
      - hyprland
      - hyprpaper
      - hyprshot
      - hyprlock
      - hypridle
      - waybar
      - wofi
      - swaync
      - sddm
      - ttf-font-awesome
    aur_hyprland_packages:
      - wlogout
    sddm_user: "vijay"
    sddm_session: hyprland

  tasks:
    - name: Update package database
      community.general.pacman:
        update_cache: yes

    - name: Install Hyprland packages
      community.general.pacman:
        name: "{{ hyprland_packages }}"
        state: present
        update_cache: no

    - name: Create the `aur_builder` user
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        mode: 0644
        validate: "/usr/bin/visudo -cf %s"

    - name: Install AUR application packages
      kewlfft.aur.aur:
        name: "{{ aur_hyprland_packages}}"
        use: yay
        state: present
      become: yes
      become_user: aur_builder

    - name: Kill `aur_builder` processes
      ansible.builtin.shell: pkill -u aur_builder || true

    - name: Remove the `aur_builder` user
      ansible.builtin.user:
        name: aur_builder
        state: absent
        remove: yes # removes home directory

    - name: Remove the sudoers file for `aur_builder`
      ansible.builtin.file:
        path: /etc/sudoers.d/11-install-aur_builer
        state: absent
    - name: Set default boot target to graphical
      ansible.builtin.systemd:
        name: graphical.target
        enabled: true

    - name: Enable and start SDDM
      ansible.builtin.systemd:
        name: sddm.service
        enabled: true
        state: started

    - name: Create SDDM config directory
      ansible.builtin.file:
        path: /etc/sddm.conf.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    # We can autologin through SDDM since we have hyprlock
    - name: Configure SDDM autologin
      ansible.builtin.copy:
        dest: /etc/sddm.conf.d/autologin.conf
        content: |
          [Autologin]
          User={{ sddm_user }}
          Session={{ sddm_session }}
        owner: root
        group: root
        mode: "0644"
