---
- name: Install Arch Linux packages
  hosts: localhost
  become: true
  gather_facts: false

  collections:
    - community.general

  vars:
    # Core system packages
    system_packages:
      - networkmanager
      - sudo
      - which
      - nvim
      - less
      - tree
      - git
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - rtkit
      - reflector
      - rsync
      - openssh
      - unzip
      - ripgrep
      - btop
      - dysk
      - fzf

    # Desktop environment packages
    desktop_packages:
      # KDE - Plasma
      - plasma-meta
      - sddm
      - sddm-kcm
      - qt5-declarative
      - kvantum
      - dolphin
      - ark
      - solaar
        #i3 Windows Manager
      - xorg
      - xorg-xinit
      - i3-wm
      - i3lock
      #- xautolock # Not available on pacman, use yay instead
      - i3blocks
      - i3status
      - dmenu
      - feh
      - ttf-font-awesome
      - ttf-jetbrains-mono
      - terminus-font
      - ttf-nerd-fonts-symbols
      - picom
      - dolphin
      - materia-gtk-theme
      - papirus-icon-theme
      - lxappearance
      - arandr
      - rofi
      - fuse2
      - pacman-contrib
      - libnotify
      - dunst
      - xdotool
      - ttf-nerd-fonts-symbols-mono
      - shellcheck
      - cmake

    # Graphics and display packages
    graphics_packages:
      - nvidia-open
      - nvidia-settings

    # Terminal and applications
    app_packages:
      - kitty
      - firefox
      - maim
      - calibre
      - mupdf
      - zathura
      - newsboat
      - emacs
      - fd
      - steam

    # Bluetooth packages
    bluetooth_packages:
      # There is bug with a2dp sink.
      # - bluez
      # - bluez-utils
      - blueman

    # Package management and development
    dev_packages:
      - flatpak
      - python-pip
      - python-ansible
      - base-devel

    # Combine all packages
    all_packages: "{{ system_packages + desktop_packages + graphics_packages + app_packages + bluetooth_packages + dev_packages }}"

  tasks:
    - name: Update package database
      community.general.pacman:
        update_cache: yes
      register: pacman_update

    - name: Install system packages
      community.general.pacman:
        name: "{{ system_packages }}"
        state: present
        update_cache: no
      register: system_install

    - name: Install desktop environment packages
      community.general.pacman:
        name: "{{ desktop_packages }}"
        state: present
        update_cache: no
      register: desktop_install

    - name: Install graphics packages
      community.general.pacman:
        name: "{{ graphics_packages }}"
        state: present
        update_cache: no
      register: graphics_install

    - name: Install application packages
      community.general.pacman:
        name: "{{ app_packages }}"
        state: present
        update_cache: no
      register: app_install

    - name: Install bluetooth packages
      community.general.pacman:
        name: "{{ bluetooth_packages }}"
        state: present
        update_cache: no
      register: bluetooth_install

    - name: Install development packages
      community.general.pacman:
        name: "{{ dev_packages }}"
        state: present
        update_cache: no
      register: dev_install

    - name: Enable and start NetworkManager
      systemd:
        name: NetworkManager
        enabled: yes
        state: started
      when: system_install is changed or system_install is success

    - name: Enable and start SDDM
      systemd:
        name: sddm
        enabled: yes
        state: started
      when: desktop_install is changed or desktop_install is success

    - name: Enable and start bluetooth service
      systemd:
        name: bluetooth
        enabled: yes
        state: started
      when: bluetooth_install is changed or bluetooth_install is success

    - name: Display installation summary
      debug:
        msg: |
          Package installation completed successfully!

          Installed packages by category:
          - System: {{ system_packages | length }} packages
          - Desktop: {{ desktop_packages | length }} packages  
          - Graphics: {{ graphics_packages | length }} packages
          - Applications: {{ app_packages | length }} packages
          - Bluetooth: {{ bluetooth_packages | length }} packages
          - Development: {{ dev_packages | length }} packages

          Total packages installed: {{ all_packages | length }}

          Next steps:
          1. Reboot the system to ensure all services start properly
          2. Configure SDDM display manager if needed
          3. Set up NetworkManager connections
          4. Configure bluetooth devices
          5. Install Flatpak applications as needed
        # - slack-desktop
        # - rofi-greenclip

# Need to install these packages using yay
